### ISSUE TITLE
Monoid and Cookies

### ISSUE THREAD

**Issue by nilius** [scala-hamburg/scala-hamburg#18]
"Monoid is an algebraic structure with a single associative binary operation and an identity element …". Excuse me, what are you trying to tell me?! 

Seriously, if this is too abstract for you - this is the right talk for you. Felix is going to explain, why Monoids are so useful! And even better, there are going to be cookies involved, which adds some sugar to the presentation.

Anyway, this is a perfect talk for beginner who want to take a deeper step into the category theory forest, without getting sucked into mathematical details ;-)

Felix Eckhardt, RISK IDENT

Felix Eckhardt is the CTO of RISK IDENT. RISK IDENT builds software in Scala to fight the existing online fraud.

**Comment by bijancn** [comment]
Hi Felix. Can you give more details on what you plan to cover and how long the talk will be as I wanted to do something related and dont want to overlap ;)

**Comment by nilius** [comment]
Hi Bijan, I will forward your question to Felix. I think the talk will be ~20 minutes.

**Comment by don41382** [comment]
hey @bijancn, no worries :) I would like to focus on the following things:

- how does it work? 
- simple coding example with Scala, with a cookie example
- how is it useful in the real world?

does this help you? if you keen, you could also take-over my presentation spot.

**Comment by bijancn** [comment]
Hi @don41382

Thats fine. It's a different topic then. Go ahead and have fun ;)

Felix Eckhardt <notifications@github.com> schrieb am Do., 5. Juli 2018,
10:41:

**Comment by mattelacchiato** [comment]
Will be held on July, 24th.
