### ISSUE TITLE
Protobufs in Scala

### ISSUE THREAD

**Issue by nilius** [scala-hamburg/scala-hamburg#19]
"Ever had to build a project using JSON, and managing data format quickly got out of hands? Complexity with Schema changes and [T]ype safety quickly followed thereafter.

Then look no further as Protobuf (Protocol Buffers) do just that. Not only do they solve the problem of schema evolution but are also suited for cross-team data sharing, which has become ever so prominent these days with the rise in microservices.
This talk is aimed at providing an insight into the serialization format and how it addresses these pain points, followed by a look into ScalaPB - a library to assist in the incorporation of protobufs in Scala."

Mahbub Alam, RISK IDENT

Mahbub is a Scala developer at RISK IDENT with a passion for experimenting new ideas and simplifying processes down-the-line.

**Comment by mattelacchiato** [comment]
Will be held on July, 24th.

**Comment by mattelacchiato** [comment]
Will be held on July, 24th.
