### ISSUE TITLE
Talk: teleproto - a macro based library for ScalaPB API evolution

### ISSUE THREAD

**Issue by christoph-wulf-moia** [scala-hamburg/scala-hamburg#21]
**Description**
Protocol Buffers are a great tool for communication between micro-services, especially in a polyglot setup. ScalaPB is very useful to deal with Protocol Buffers in Scala but has its limitations in handling the mismatch between PB and Scala.
teleproto - developed at moia.io - is a Scala macro based library to map generated ScalaPB classes to plain old Scala structures. It also helps in managing API evolution with incompatible changes.

This talk introduces the problem and the solution using Scala macros. It also shows the capabilities of meta-programming with macros and gives some hints in which cases they are really useful.

**Bio**
I started to work with Scala in 2009 and wrote my master thesis about a compiler plug-in for type-safe SQL in Scala. Later I migrated that approach to Scala macros and found other applications for macros in several Scala projects. In recent years I focused on Scala projects with data at scale using Spark, Kafka, Akka and Play.

**Comment by christoph-wulf-moia** [comment]
@mattelacchiato Could you please assign me and add labels _proposal_ and _advanced_? Thanks!

**Comment by magro** [comment]
Hey @christoph-wulf-moia, we're currently planning a meetup for the 9th of October, for which #24 is scheduled so far. Do you want to give the talk on teleproto at that meetup as well? Another option would be to do this next week, the 22nd of August ([meetup](https://www.meetup.com/de-DE/Scala-Hamburg/events/263358989/)).

**Comment by christoph-wulf-moia** [comment]
@magro 9th of October is fine, next week I am on vacation. Should I align for 30 minutes, then?

**Comment by magro** [comment]
@christoph-wulf-moia Great! 30 minutes sounds good, if it's only 20 that's also fine...

**Comment by markusjura** [comment]
Scheduled for 09.10.2019
