### ISSUE TITLE
Talk: How to build a full app with ZIO

### ISSUE THREAD

**Issue by don41382** [scala-hamburg/scala-hamburg#22]
This talk is about how you build an app from scratch and how ZIO can provide the perfect testable environment.

Following frameworks will be used:
- http4s
- doobie
- circe 

I would like to make two parts out of this talk. Each talk 20/30 minutes.

**Comment by lutzh** [comment]
Sounds good. When you say 2 parts, you mean you would also like to spread it over two dates/events?

**Comment by don41382** [comment]
Hey Lutz,

Yes, I would like to split the talk into two meetup sessions.

I think one hour is too much to digest :)

Cheers,
Felix

**Comment by lutzh** [comment]
Sure, no problem. 
I guess you would like to host it as Risk.Ident? If you like we can set a date and time and we (the organizers)  will find another short talk & speaker to complement your talk. If there is a few weeks lead time I'm sure that won't be a problem.

**Comment by don41382** [comment]
Yes, that would be nice. I asked in our company and found somebody else, who like to give a short talk too. I think we could have 3x 20/30 minute talks.

Wdyt? Have a nice weekend.

Cheers,
Felix

**Comment by lutzh** [comment]
Scheduled for August 22, 2019
