### ISSUE TITLE
Talk: Turning runtime errors into compile time errors using Phantom types

### ISSUE THREAD

**Issue by alexvanolst** [scala-hamburg/scala-hamburg#23]
For the same event as: https://github.com/scala-hamburg/scala-hamburg/issues/22

The talk would be a 2--25 min tour of some ways you can use phantom types to encode constraints and turn what would be run time errors into compile time errors. 

edit: I don't have permission to label this so if someone could do so that would be great.

**Comment by lutzh** [comment]
Scheduled for August 22, 2019

**Comment by don41382** [comment]
@lutzh it is not closed, due to timing issue it was not presented on the last meetup. So this should be scheduled for October.

If we don't have enough room, I would offer to switch it with my ZEO talk.

**Comment by lutzh** [comment]
Oops. I didn't know since I wasn't there. Also won't be at the next one... @mattelacchiato @don41382 maybe you can synch to update https://www.meetup.com/de-DE/Scala-Hamburg/events/264213490/ ?

**Comment by alexvanolst** [comment]
I just checked and I will be on vacation on the 9th so @don41382 can go ahead with the ZIO talk. I'll reopen this when the timing works out.
