### ISSUE TITLE
Build yourself an effect system 

### ISSUE THREAD

**Issue by runtologist** [scala-hamburg/scala-hamburg#25]
So you dig IO Monads. All your effects are represented using types via libraries such as ZIO or Cats Effect. Now what? At some time you'll have to unsafeRun your effect. What will happen then?

During this talk we'll build a minimal effect runtime similar to the one used in ZIO. We'll learn how effects can get executed and how parallelism and concurrency can be implemented using fibers aka green threads.

**Comment by runtologist** [comment]
thx for labelling, @lutzh. :)

**Comment by lutzh** [comment]
Six upvotes already, I think this talk will be happening. @runtologist a few small questions:
- we usually have 1 talk per evening. Is that also how you'd like it?  (If the talk <= 30 minutes we could consider multiple talks)
- would you like to host it at your employer, or should we find a host for the evening?
- maybe suggest some dates when you'd like to give the talk? (not within 3 weeks before or after 9.10., as that's already set for the October event).

**Comment by runtologist** [comment]
I think 20 or 30 minutes will be too short, so this will be a "full" talk. We currently do not have enough space to host the event with the normal number of attendees, so finding a host would be great. How about 6 November?

**Comment by markusjura** [comment]
@runtologist We organizers would be very happy if you could give the talk on 06.11. Inoio is hosting the event. Could you provide us the following information so that we can create the event on meetup.com:
* short bio
* duration of the talk

BTW: I am labeling the issue now as `scheduled` and set the milestone to `2019-11`. This marks that the talk is scheduled for the respective meetup even so it is not on meetup.com yet.

**Comment by markusjura** [comment]
@runtologist @mattelacchiato We have another talk proposal by Nikita (@meln1k) https://github.com/reactive-systems-hamburg/reactive-systems-hamburg/issues/8 for the reactive systems meetup. Nikita gives the same talk at ScalaConf Russia on 26.11. Therefore, he would like to give the talk in Hamburg between 28.10 - 15.11.

I'd suggest the following:
1. Nikita gives his talk at 31.10. Hosted at MOIA
2. Simon gives his talk between 19.11 - 21.11. Does it work for @runtologist and @mattelacchiato  (hosting)?

This way, we would have 3 weeks' pause between each talk. In December we have another talk scheduled which we then can do in the second week of December before people go on Christmas vacation.

**Comment by markusjura** [comment]
Also, I am in contact with John De Goes and he might have the chance to come to Hamburg at 26.10. and give a talk. I'll clarify it at the latest next week. If that is the case I'd suggest squeezing a talk by John in as well. Then Nikita could give a talk in the first week of November and Simon in the last week of November. Would that also work for you, Simon and Matthias?

**Comment by mattelacchiato** [comment]
We would have to check the dates here internally. Some of us are currently on vacation, but I'm pretty sure that we could handle it. But let's first wait on @runtologist to approve the suggested dates...

**Comment by runtologist** [comment]
Simon builds distributed and data intensive applications. Since 2012 most of these have been written in Scala in the domains of multimedia search, online comparison sites and risk assessment.
Simon is CTO at Risk42, a fintech startup doing payment risk assessment and consumer credit scoring using machine learning. 

The duration will be 60 minutes.

**Comment by runtologist** [comment]
Last week of November still is completely free and would actually be better for me than 19.-21. If there are no restrictions at Inoio, I'd have a slight preference for Tuesday 26. or Thursday 28., but any other day would be possible.

**Comment by mattelacchiato** [comment]
Tuesday 26th is great for us. Any objections, @markusjura ?

**Comment by markusjura** [comment]
No, let’s make Tuesday, 26.11. fix. Thanks for the flexibility.

**Comment by magro** [comment]
Now it's published: https://www.meetup.com/de-DE/Scala-Hamburg/events/265681417/
