### ISSUE TITLE
Integrating Developer Experiences - Build Server Protocol and Beyond

### ISSUE THREAD

**Issue by jastice** [scala-hamburg/scala-hamburg#28]
## Talk

IDEs - Integrated Development Environments - traditionally provide out of the box support for many of the tasks that go into making working software out of source code. But increasingly, developers expect to be able to use any one of a variety of special-purpose tools for each task. This shifts the focus of the IDE from "Integrated" to "Integrating" external tools into a coherent experience. 

Especially in the Scala ecosystem, we have an increasing number of build tools to choose from. I have been focusing on integrating sbt and other new tools with the IntelliJ Scala plugin and will talk about challenges involved and how the Build Server Protocol makes it possible for IntelliJ to interface with any build tool.

## Bio

Justin believes in "Tools before Rules": 
automating the development toolchain to remove the friction of dealing with manual processes. He works on this goal as part of the IntelliJ Scala plugin team.

-----

Talk is ready.

**Comment by markusjura** [comment]
Talk is scheduled for 16.01.2020

**Comment by markusjura** [comment]
https://www.meetup.com/Scala-Hamburg/events/267319099/?isFirstPublish=true
