### ISSUE TITLE
Sleeping well in the lion's den with Monix Catnap

### ISSUE THREAD

**Issue by Avasil** [scala-hamburg/scala-hamburg#29]
Hello, Hamburg!

### Abstract

Concurrency bugs leave you restless? Monix Catnap provides a ton of utilities that will let your worries take a good nap!

Monix Catnap and Execution are rather unknown modules of Monix which have a lot of useful features like Local, ConcurrentQueue and ConcurrentChannel for everyone to use regardless of their effect of choice.

The talk will cover some of the most interesting ones and show how they could be of use in your projects.

### Bio

One of the maintainers of Monix and Kraków Scala User Group organisers. I work at VirtusLab and spend most of my free time on open source and other nerdy hobbies.

**Comment by markusjura** [comment]
Scheduled for 12.02.
