### ISSUE TITLE
Declarative concurrency with ZIO STM

### ISSUE THREAD

**Issue by mijicd** [scala-hamburg/scala-hamburg#31]
Hello Hamburg! 

I'd like to give a talk about ZIO's STM. Please find below the short abstract and my bio.

### Abstract

Software transactional memory (STM) is an abstraction analogous to database transactions used to build safe, composable and modular code dealing with concurrency.

In this talk, Dejan will present the building blocks of STM implementation available in ZIO library. He'll demonstrate how to use the STM and its accompanying structures (e.g. TRef, TQueue etc.) and discuss their internal implementation details.

### Biography

Dejan Mijic works as a senior software engineer at Zalando SE in Berlin, Germany. He is passionate about functional programming and distributed systems. Outside of his daily job, he enjoys contributing to OSS projects and competing in general knowledge quizzes.

**Comment by markusjura** [comment]
Scheduled: https://www.meetup.com/Scala-Hamburg/events/268977226/
