### ISSUE TITLE
Performance tuning with sbt-jmh

### ISSUE THREAD

**Issue by magro** [scala-hamburg/scala-hamburg#5]
**Summary**
A short introduction to microbenchmarks in general, how to do this with JMH and how to integrate sbt-jmh into a scala/sbt project.

**Meetup Announcement**
Every once in a while every one of us is trying to measure performance of certain parts of the code. Maybe because we've identified some piece of code in the "hot path" as a bottleneck, or just because there are different implementation variants where we'd like to choose the fastest one.
Unfortuntunately, obtaining meaningful numbers is actually difficult on the JVM, i.e. the plain timing style of t2-t1 may be misleading or is at least questionable. Providing a meaningful benchmark that has accurate and reproducible results is not trivial.

In this talk I’d like to introduce JMH, the Java Microbenchmarking Harness, which was created for exactly this purpose and gives us a solid foundation for writing benchmarks. We'll see how we can integrate it into our Scala project / build, and how we can write microbenchmarks with JMH.

**Bio**
Martin is co-founder of inoio, building distributed systems with Scala.

**Comment by mattelacchiato** [comment]
Can be closed. Will be held at https://www.meetup.com/de-DE/Scala-Hamburg/events/251207492/
