### ISSUE TITLE
Typelevel computation with Typedapi

### ISSUE THREAD

**Issue by pheymann** [scala-hamburg/scala-hamburg#6]
**labels**: proposal, type-level, shapeless, intermediate, advanced

Last evening I spoke with @magro about my Typelevel Summit talk I will give next month:
   
  https://typelevel.org/event/2018-05-summit-berlin/

And he suggested that it might be also a candidate for a Meetup talk. I agree with that but I won't be ready with it until after the Summit, which should be fine, because:
 1. just small number of our Meetup participants will participate in the Summit
 2. I only have 15min during the Summit to present my ideas and the library which puts constraints on how in-depth I can explain certain concepts of type-level computations. On the other hand, I probably have more time for explanations during a Meetup talk.

### Proposal
Have you ever thought “I really like Haskell’s Servant. Why don’t we have something like that in Scala?” or “Why can't I just define my APIs as types and Scala does the heavy lifting?”? If so, this talk is made for you.

I will tell you a short story about excitement, pain and hate peaking in a climax of type-driven enlightenment. I will tell you my journey of developing [Typedapi](https://github.com/pheymann/typedapi/), a library for building typesafe APIs which moves as many computations to the type level as possible.

We will fight many a beast on our way from Scala’s desugaring to folds working just on types. But eventually, we will arrive at our destination, exhausted, with scars but also able to make our code a bit safer again.

**Comment by mattelacchiato** [comment]
Will be held at https://www.meetup.com/de-DE/Scala-Hamburg/events/251207492/
